---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - tifffile =2025.6.11
  - numpy =1.26.4
  - typer =0.16.0
  - pyarrow =18.1.0
  - rasterio =1.4.3
  - shapely =2.0.6
